name: Huawei push package

on:
  release:
    types: [created]

jobs:
  publish-pkg:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Authenticate gh repo
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GHCR_TOKEN }}\n$(cat .npmrc)" > .npmrc
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: cat .npmrc
      - run: npm publish --verbose
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}